#! docker-compose
services:
  lottery-service-db:
    image: postgres:15.8
    environment:
      - POSTGRES_USER=lottery_service
      - POSTGRES_PASSWORD=lottery_service
      - POSTGRES_DB=lottery-service
    ports:
      - "5432:5432"
    labels:
      lottery_service: "lottery_service"