INSERT INTO Lottery (name, modality, description)
VALUES ('Mega-Sena', 'MEGA_SENA',
        'A Mega-Sena é a loteria que paga milhões para o acertador dos 6 números. Para apostar você escolhe de 6 a 15 números, entre os 60 disponíveis no volante.' ),
       ('Lotofácil', 'LOTOFACIL',
        'A Lotofácil é a loteria certa para você que gosta de apostar e, principalmente, ganhar. Você pode marcar de 15 a 20 números, entre os 25 disponíveis no volante.'),
       ('Quina', 'QUINA',
        'Na Quina, você aposta de 5 a 15 números, entre os 80 disponíveis, e concorre a prêmios de valores grandiosos.'),
       ('Lotomania', 'LOTOMANIA',
        'Na Lotomania, você escolhe 50 números e ganha se acertar 15, 16, 17, 18, 19, 20 ou nenhum número. Ela é simples de apostar e fácil de ganhar.'),
       ('Timemania', 'TIMEMANIA',
        'No Timemania, seu palpite pode valer uma bolada. São oitenta números e oitenta clubes de futebol, você escolhe dez números e um time do coração.'),
       ('Dupla Sena', 'DUPLA_SENA',
        'Na Dupla Sena, você tem o dobro de chances de ganhar. Com o mesmo bilhete, você participa de dois sorteios por concurso e ganha se acertar 3, 4, 5 ou 6 números.'),
       ('Federal', 'LOTERIA_FEDERAL',
        'Na Federal é muito mais fácil ganhar. Você tem diversas chances de acertar o prêmio principal, e também pode ganhar se acertar uma das outras opções de aposta.'),
       ('Loteca', 'LOTECA',
        'A Loteca é a loteria ideal para você que entende de futebol e adora dar palpites sobre os resultados das partidas. Para apostar, você deve marcar o seu palpite para cada um dos 14 jogos do concurso.'),
       ('Dia de Sorte', 'DIA_DE_SORTE',
        'O Dia de Sorte é a loteria em que você aposta seus números da sorte. Escolha de 7 a 15 números dentre os 31 disponíveis e mais 1 “Mês de Sorte”. São sorteados sete números e um “Mês de Sorte” por concurso.'),
       ('Super Sete', 'SUPER_SETE',
        'O Super Sete tem o mote “colunas”, em que o apostador marca, no mínimo, 1 número em cada uma das 7 colunas e no máximo 3 por coluna. Você ganha prêmios se acertar de três a sete colunas, independentemente da ordem.'),
       ('+Milionária', 'MAIS_MILIONARIA',
        'A +Milionária é a mais nova loteria da CAIXA. São dez faixas de premiação e prêmio mínimo garantido de R$ 10 milhões a cada sorteio.');
